name: Trivy Scan

on:
  push:
    branches: ["debug-trivy-scan-issue"]
    paths:
      - ".github/workflows/trivy.yml"
  pull_request:
    branches: ["debug-trivy-scan-issue"]
    paths:
      - ".github/workflows/trivy.yml"

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: echo $CR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Verify Image Existence
        run: |
          if ! docker pull --platform linux/amd64 ghcr.io/rajanagori/nightingale:stable; then
            echo "Docker image not found for amd64. Trying arm64."
            exit 1
          fi

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db
          restore-keys: |
            ${{ runner.os }}-trivy-db

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.57.0/trivy_0.57.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.57.0_Linux-64bit.deb
          trivy --cache-dir ${HOME}/.cache/trivy

      - name: Run Trivy vulnerability scanner
        run: |
          export TRIVY_AUTH_URL="https://ghcr.io"
          export TRIVY_TOKEN=$GITHUB_TOKEN
          for i in {1..5}; do
            trivy image \
              --skip-dirs /home/wordlist \
              --skip-files home/tools_web_vapt/WhatWeb/plugins/IpToCountry.csv \
              --format sarif \
              --output trivy-results.sarif \
              --severity CRITICAL \
              ghcr.io/rajanagori/nightingale:stable && break || sleep 60
          done

      - name: Debug Trivy Results
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "Trivy results file generated successfully." && cat trivy-results.sarif
          else
            echo "Failed to generate Trivy results file." && exit 1
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Save SARIF file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.sarif