name: Trivy Scan

on:
  push:
    branches: ["debug-trivy-scan-issue"]
    paths:
      - ".github/workflows/trivy.yml"
  pull_request:
    branches: ["debug-trivy-scan-issue"]
    paths:
      - ".github/workflows/trivy.yml"

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: echo $CR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Verify Image Existence
        run: |
          if ! docker pull --platform linux/amd64 ghcr.io/rajanagori/nightingale:stable; then
            echo "Docker image not found for amd64. Trying arm64."
            if ! docker pull --platform linux/arm64 ghcr.io/rajanagori/nightingale:stable; then
              echo "Docker image not found for arm64."
              exit 1
            fi
            exit 1
          fi

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db-${{ github.sha }}-${{ github.run_id }}-${{ env.cache_key }}
          restore-keys: |
            ${{ runner.os }}-trivy-db-${{ env.cache_key }}

      - name: Set cache key based on the date
        id: date
        run: |
          echo "cache_key=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.57.0/trivy_0.57.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.57.0_Linux-64bit.deb
      
      - name: Check cache age and refresh Trivy DB if expired
        run: |
          CACHE_PATH="${HOME}/.cache/trivy/db"
          CACHE_AGE=$(( $(date +%s) - $(stat -c %Y "$CACHE_PATH") ))
          MAX_AGE=$((24 * 60 * 60))  # 24 hours in seconds

          if [ $CACHE_AGE -gt $MAX_AGE ]; then
            echo "Cache is older than 24 hours. Refreshing Trivy database..."
            trivy --cache-dir ${HOME}/.cache/trivy --refresh  # Refresh the database if the cache is expired
          else
            echo "Cache is fresh. Skipping Trivy database refresh."
          fi

      - name: Run Trivy vulnerability scanner
        run: |
          export TRIVY_AUTH_URL="https://ghcr.io"
          export TRIVY_TOKEN=$GITHUB_TOKEN
          for i in {1..5}; do
            trivy image \
              --skip-dirs /home/wordlist \
              --skip-files home/tools_web_vapt/WhatWeb/plugins/IpToCountry.csv \
              --format sarif \
              --output trivy-results.sarif \
              --severity CRITICAL,MEDIUM \
              ghcr.io/rajanagori/nightingale:stable && break || sleep 60
          done

      - name: Generate SPDX SBOM
        run: |
          if ! trivy image \
              --format spdx \
              --scanners vuln \
              --output sbom.spdx.json \
              ghcr.io/rajanagori/nightingale:stable; then
            echo "Warning: SPDX SBOM generation failed or lacked necessary compliance info."
          fi

      - name: Generate CycloneDX SBOM
        run: |
          if ! trivy image \
              --format cyclonedx \
              --scanners vuln \
              --output sbom.cyclonedx.json \
              ghcr.io/rajanagori/nightingale:stable; then
            echo "Warning: CycloneDX SBOM generation failed or lacked necessary security info."
          fi

      - name: Save SARIF & SBOMs file as an artifact
        uses: actions/upload-artifact@v3
        with:- name: Create a ZIP file for artifacts
        run: |
          mkdir -p artifacts
    
          mv trivy-results.sarif artifacts/
          mv sbom.spdx.json artifacts/
          mv sbom.cyclonedx.json artifacts/

          zip -r artifacts.zip artifacts/

      - name: Upload the ZIP file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-artifacts
          path: artifacts.zip