name: Trivy Scan

on:
  push:
    branches: ["debug-trivy-scan-issue"]
    paths:
      - ".github/workflows/trivy.yml"
  pull_request:
    branches: ["debug-trivy-scan-issue"]
    paths:
      - ".github/workflows/trivy.yml"

permissions:
  contents: read
  security-events: write

jobs:
  setup:
    name: Setup and Fetch Images
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.fetch_images.outputs.images }}
    steps:
      - name: Authenticate with GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.TOKEN }}
        run: echo $CR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Fetch Stable Images from GitHub Container Registry
        id: fetch_images
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Fetching stable images from GitHub Container Registry..."
          RESPONSE=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/users/RAJANAGORI/packages?package_type=container")

          echo "API Response: $RESPONSE"

          # Use jq to safely extract image names
          IMAGES=$(echo "$RESPONSE" | jq -r 'map(select(.package_type == "container")) | .[].name')

          STABLE_IMAGES=()
          for PACKAGE in $IMAGES; do
            TAGS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/users/RAJANAGORI/packages/container/${PACKAGE}/versions?per_page=100" \
              | jq -r '[.[] | .metadata.container.tags[]] | map(select(. | contains("stable"))) | .[]' || echo "")

            for TAG in $TAGS; do
              STABLE_IMAGES+=("ghcr.io/RAJANAGORI/${PACKAGE}:${TAG}")
            done
          done

          echo "Stable images found: ${STABLE_IMAGES[*]}"
          echo "::set-output name=images::$(jq -c -n '$ARGS.positional' --args "${STABLE_IMAGES[@]}")"

  download:
    name: Pre-download Trivy DB and Images
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget jq

      - name: Cache Trivy Database
        id: cache_trivy
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-cache

      - name: Refresh Trivy Database if Needed
        if: steps.cache_trivy.outputs.cache-hit != 'true'
        run: trivy image --download-db-only

      - name: Pre-pull and Save Docker Images
        run: |
          mkdir -p shared
          IMAGES=${{ needs.setup.outputs.images }}
          for IMAGE in $(echo "$IMAGES" | jq -r '.[]'); do
            docker pull $IMAGE || exit 1
            IMAGE_NAME=$(echo $IMAGE | sed 's/[^a-zA-Z0-9]/_/g')
            docker save $IMAGE > shared/${IMAGE_NAME}.tar
          done

      - name: Compress Shared Files
        run: zip -r shared-images.zip shared/

      - name: Upload Shared ZIP
        uses: actions/upload-artifact@v3
        with:
          name: shared-images
          path: shared-images.zip

  scan:
    name: Trivy Scan
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.setup.outputs.images) }}
    steps:
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y wget jq

      - name: Download and Extract Shared ZIP
        uses: actions/download-artifact@v3
        with:
          name: shared-images
        run: unzip shared-images.zip

      - name: Load Pre-pulled Docker Image
        run: |
          IMAGE_NAME=$(echo "${{ matrix.image }}" | sed 's/[^a-zA-Z0-9]/_/g')
          docker load < shared/${IMAGE_NAME}.tar

      - name: Run Trivy Vulnerability Scanner (SARIF and CycloneDX)
        run: |
          echo "Scanning ${{ matrix.image }}..."
          trivy image \
            --format sarif \
            --output trivy-results-${{ matrix.image }}.sarif \
            --severity CRITICAL,MEDIUM \
            ${{ matrix.image }}

          trivy image \
            --format cyclonedx \
            --scanners vuln \
            --output sbom-${{ matrix.image }}.cyclonedx.json \
            --severity CRITICAL,MEDIUM \
            ${{ matrix.image }}

      - name: Prepare ZIP File for Artifacts
        run: |
          mkdir -p artifacts
          mv trivy-results-${{ matrix.image }}.sarif artifacts/
          mv sbom-${{ matrix.image }}.cyclonedx.json artifacts/
          zip -r trivy-artifacts-${{ matrix.image }}.zip artifacts/

      - name: Upload Artifacts (Single ZIP)
        uses: actions/upload-artifact@v3
        with:
          name: trivy-artifacts
          path: trivy-artifacts-${{ matrix.image }}.zip
